services:
  - type: web
    name: garagefy-backend
    runtime: python
    region: frankfurt
    plan: free
    branch: clean-garagefy
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        value: appaZpcXMlL5JqJBc
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_TENANT_ID
        sync: false
      - key: EMAIL_ADDRESS
        value: info@garagefy.app
      - key: CLOUDINARY_CLOUD_NAME
        value: dteblwsuu
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
